name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Kafka Producer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/kafka-producer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kafka-producer:latest

      - name: Build and push Kafka Consumer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/kafka-consumer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kafka-consumer:latest

      - name: Build and push NLP App image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/nlp-app/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nlp-app:latest

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run docker-compose
        run: |
          docker-compose up -d
          sleep 30
          docker ps
