name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Kafka Producer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile   # ✅ use the root Dockerfile
          push: true
          tags: ghcr.io/momkhan1/enterprise-ai-nlp-solution/kafka-producer:latest

      - name: Build and push Kafka Consumer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile   # ✅ same root Dockerfile
          push: true
          tags: ghcr.io/momkhan1/enterprise-ai-nlp-solution/kafka-consumer:latest
